version: '3.3'
volumes:
  postgres_data: {}
  bundle_box: {}

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    
    #entrypoint: ./docker-entrypoint.sh
    env_file:
      - ./.env
    # environment:
      # POSTGRES_PASSWORD: password
      # DATABASE_URL: pgsql://your_user:your_password@database.host/database.name
    depends_on:
      - postgres  
    volumes:
      - bundle_box:/bundle-box
      - .:/app
    ports:
      - 7700:8000

  postgres:
    image: postgres
    restart: always
    # environment:
    #   POSTGRES_PASSWORD: akileebox
    #   POSTGRES_USER: akilee
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/paycore/postgresql/data
    ports:
      - 7654:5432
