version: '3.3'
volumes:
  postgres_data: {}
  bundle_box: {}

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    
    #entrypoint: ./docker-entrypoint.sh
    env_file:
      - ./.env
    depends_on:
      - postgres  
    volumes:
      - bundle_box:/bundle-box
      - .:/app
    ports:
      - 8000:8000

  postgres:
    image: postgres
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/paycore/postgresql/data
    ports:
      - 7654:5432
